# Generated by Django 5.1.15 on 2026-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/3789/3789820.png'),
        ),
    ]
