services:
  - type: web
    name: job-portal
    runtime: python
    pythonVersion: 3.14
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn job_portal_django.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-j7%9$d*7@x#q1a!z_5e8w$q+2a#h!y&d8#q)t@x_c8p2e&q+c"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: neon
          property: connectionString
